"""
Generate docs/furnishing-schedule.md.

    python3 blender/make_docs.py

Written from the pipeline's own outputs rather than by hand, so the counts
in the document are the counts in the model.

PHASE 7 — this no longer writes docs/asset-register.md. The register now has
to carry Poly Haven provenance (creator, licence, retrieval date, source
polycount, packed texture resolution) and none of that is reachable from
build-stats.json alone; it lives in tools/polyhaven/assets.json and
public/scene/tex/manifest.json. The register is generated by
`node tools/polyhaven/generate-register.mjs`, which reads all three. Both
scripts writing the same file was a race with a silent loser.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, 'config'))

from palette import PALETTE
from rooms import SCHEDULE, FINISH_ASSETS, MOBILE_DROP, MOBILE_DROP_LEVELS

# Footprints and clearances are read from build-stats.json rather than
# imported: asset_loader needs bpy, and the parameter variants only exist
# once the library has been built.
FOOTPRINT = {}
CLEARANCE = {}

DOCS = os.path.abspath(os.path.join(HERE, '..', 'docs'))


def load(name):
    with open(os.path.join(HERE, 'out', name)) as fh:
        return json.load(fh)


def kb(n):
    return f'{n / 1024:.1f} kB'


# `asset_register()` lived here until Phase 7. It was deleted rather than
# left unused: two scripts that can both write docs/asset-register.md is a
# race whose loser is silent, and this one can no longer see the provenance
# the register has to carry. See tools/polyhaven/generate-register.mjs.

def furnishing_schedule(st, plan):
    rooms = st['rooms']
    levels = plan['levels']
    q = plan['quantities']
    lines = ["""# Furnishing schedule — GoDataFusion environment

PHASE 8: THREE LEVELS.

The building is the site's own plan, and it is not described here.
`src/webgl/levels.js` declares the room rectangles of L00, L01 and L02 and
DERIVES the walls, the doors and the windows from them;
`blender/dump_plan.mjs` imports that module and dumps exactly what it
computes; `blender/build_environment.py` extrudes the dump. No dimension in
this document was chosen independently of the drawings the QUANTIFY mode
counts, and nothing in it was typed.

What IS authored by hand is the one thing a plan cannot know: what stands in
each room. That is `blender/config/rooms.py`, and it is the table below.

| Derived quantity | Value |
| --- | --- |"""]
    lines += [
        f"| Metres per world unit | {plan['metresPerUnit']:.4f} "
        f"(solved from 842.6 m2 over 6.4 x 4.6 units) |",
        f"| Footprint (L00, L01) | {(levels[0]['x1'] - levels[0]['x0']) * plan['metresPerUnit']:.2f}"
        f" x {(levels[0]['z1'] - levels[0]['z0']) * plan['metresPerUnit']:.2f} m |",
        f"| Footprint (L02) | {(levels[2]['x1'] - levels[2]['x0']) * plan['metresPerUnit']:.2f}"
        f" x {(levels[2]['z1'] - levels[2]['z0']) * plan['metresPerUnit']:.2f} m"
        f" — set back one structural bay |",
        f"| Roof terrace | {q['total']['terraceArea']:.1f} m2, over the L01 east bay |",
        f"| Building height | +{plan['roof']['elevation']:.2f} m to the roof datum, "
        f"+{plan['roof']['elevation'] + plan['roof']['parapet']:.2f} m over the parapet |",
        f"| Levels | {q['total']['levels']} + roof |",
        f"| Rooms | {q['total']['rooms']} |",
        f"| Doors | {q['total']['doors']}, derived from which rooms touch circulation |",
        f"| Windows | {q['total']['windows']}, one per structural bay the room covers |",
        f"| Gross internal area | {q['total']['area']:.1f} m2 |",
        "",
        "## Levels",
        "",
        "| Level | Programme | Elevation | Floor-to-floor | Clear | Rooms | Doors | Windows | Area (m2) | Furniture |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for lv in levels:
        s_ = st['levels'][lv['id']]
        lines.append(
            f"| {lv['id']} | {lv['label']} | +{lv['elevation']:.2f} m | {lv['ftf']:.2f} m |"
            f" {lv['clear']:.2f} m | {len(lv['rooms'])} | {len(lv['doors'])} |"
            f" {len(lv['windows'])} | {lv['area']:.1f} | {s_['furniture']} |")
    lines += [
        f"| ROOF | {plan['roof']['label']} | +{plan['roof']['elevation']:.2f} m | — | — |"
        f" — | — | — | — | — |",
        "",
        "The three plans are deliberately NOT variations of one grid:",
        "",
        "* **L00** four equal bays either side of one deep 8.2 m circulation",
        "  spine — twelve rooms of one size, which is what a public floor with",
        "  an unfinished bay in it wants.",
        "* **L01** the deep band is on the NORTH, the shallow one faces the",
        "  entrance, and the column rhythm is A-B-A rather than four equal",
        "  bays. That is where the 4.3 m focus rooms come from, and it is why",
        "  this floor has the most doors in the building.",
        "* **L02** the mirror of L01 — deep band south — set back a full bay",
        "  from the east facade so a roof terrace opens over L01. Fewest",
        "  rooms, largest rooms.",
        "",
        "## Programme",
        "",
        "| Room | Level | Zone | Programme | Area (m2) | Finish |",
        "| --- | --- | --- | --- | ---: | --- |",
    ]
    finish_of = {}
    for lv in levels:
        for r in lv['rooms']:
            finish_of[r['uid']] = r
    for uid in sorted(rooms):
        r = rooms[uid]
        area = (r['x1'] - r['x0']) * (r['y1'] - r['y0'])
        src = finish_of.get(uid, {})
        lines.append(f"| {uid} | {r['level']} | {r['zone']} | {r['label']} |"
                     f" {area:.1f} | {src.get('kind', '')} |")

    lines += ["", "## Schedule", "",
              "`layout` names are the placement rules in `blender/room_layout.py`.",
              "Every placement is validated against the room's walls, its door",
              "clearances and the other objects already in it; the current build",
              "drops nothing.", "",
              "Density descends by level on purpose — the ground floor is the one",
              "the hero looks into and the one CAPTURE sells, the project floor is",
              "the one a phone frame never contains.", "",
              "| Room | Asset | Count | Layout | Requirement |",
              "| --- | --- | ---: | --- | --- |"]
    for uid in sorted(SCHEDULE):
        for e in SCHEDULE[uid]:
            w, d = FOOTPRINT.get(e['asset'], (0, 0))
            extra = []
            if 'length' in e: extra.append(f"length {e['length']:.2f} m")
            if 'side' in e: extra.append(f"wall {e['side']}")
            if 'corner' in e: extra.append(f"corner {e['corner']}")
            if e['asset'] in FINISH_ASSETS: extra.append('counted as finish, not contents')
            req = f"{w:.2f} x {d:.2f} m" + (' — ' + ', '.join(extra) if extra else '')
            lines.append(f"| {uid} | `{e['asset']}` | {e['count']} | `{e['layout']}` | {req} |")

    counts = st['furniture']
    fam = {
        'seating': ('office_chair', 'meeting_chair', 'lounge_chair'),
        'tables and desks': ('desk', 'meeting_table', 'meeting_table_small',
                             'plan_table', 'side_table', 'reception_desk'),
        'screens': ('monitor', 'wall_screen'),
        'storage': ('credenza', 'credenza_small', 'shelving', 'equipment_case'),
        'lighting': ('pendant', 'ceiling_line', 'floor_lamp'),
        'plants': ('plant',),
    }
    # Phase 7's caps were written for ONE storey. Three storeys of the same
    # density would be three times the geometry for the same reading, so the
    # per-family targets are per BUILDING and grow by roughly 2.5x, not 3x —
    # the project floor is deliberately lighter than the ground floor.
    targets = {'seating': '40–56', 'tables and desks': '20–28', 'screens': '24–34',
               'storage': '12–18', 'lighting': '34–48', 'plants': '8–12'}
    lines += ["", "## Against the brief's caps", "",
              "| Family | Placed | Phase 8 target |", "| --- | ---: | --- |"]
    for k, members in fam.items():
        n = sum(counts.get(m, 0) for m in members)
        lines.append(f"| {k} | {n} | {targets[k]} |")
    lines += ["", "## Mobile tier", "",
              f"Dropped assets: {', '.join(sorted(MOBILE_DROP))}.",
              f"Dropped levels' contents: {', '.join(MOBILE_DROP_LEVELS)}.", ""]
    return '\n'.join(lines) + '\n'


def main():
    os.makedirs(DOCS, exist_ok=True)
    st, ex = load('build-stats.json'), load('export-report.json')
    with open(os.path.join(HERE, 'config', 'plan-features.json')) as fh:
        plan = json.load(fh)
    FOOTPRINT.update(st['footprint'])
    CLEARANCE.update(st['clearance'])
    with open(os.path.join(DOCS, 'furnishing-schedule.md'), 'w') as fh:
        fh.write(furnishing_schedule(st, plan))
    print('wrote docs/furnishing-schedule.md'
          '  (the asset register is generated by '
          'node tools/polyhaven/generate-register.mjs)')


if __name__ == '__main__':
    main()
